spring:
  application:
    name: rabbitmq-cluster

  rabbitmq:
    addresses: localhost:5672,localhost:5673,localhost:5674,localhost:5675
    username: guest
    password: guest
    virtual-host: app_vhost

    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 4
        max-concurrency: 8
        prefetch: 10

app:
  messaging:
    producer:
      fixed-rate-ms: 500
